var logoOriginalSvg: CAShapeLayer = {
    let rootLayer = CAShapeLayer() // Generated by Svgsus
    ({
        let layer1 = CAShapeLayer()
        layer1.fillColor = UIColor(red: 0, green: 0, blue:0, alpha: 1).CGColor
        layer1.strokeColor = UIColor(red: 0, green: 0, blue:0, alpha: 0).CGColor
        layer1.lineWidth = 0
        layer1.fillRule = kCAFillRuleEvenOdd
        rootLayer.addSublayer(layer1)
        let path = UIBezierPath()
        path.moveToPoint(CGPoint(x: 0, y: 0))
        path.addLineToPoint(CGPoint(x: 400, y: 0))
        path.addLineToPoint(CGPoint(x: 400, y: 400))
        path.addLineToPoint(CGPoint(x: 0, y: 400))
        path.closePath()
        layer1.path = path.CGPath
    })()
    ({
        let layer1 = CAShapeLayer()
        layer1.fillColor = UIColor(red: 1, green: 1, blue:1, alpha: 1).CGColor
        layer1.strokeColor = UIColor(red: 0, green: 0, blue:0, alpha: 0).CGColor
        layer1.lineWidth = 0
        layer1.fillRule = kCAFillRuleEvenOdd
        rootLayer.addSublayer(layer1)
        let path = UIBezierPath()
        path.moveToPoint(CGPoint(x: 178, y: 331.067))
        path.addLineToPoint(CGPoint(x: 96, y: 331.067))
        path.addCurveToPoint(CGPoint(x: 92, y: 327.067), controlPoint1: CGPoint(x: 93.733, y: 331.067), controlPoint2: CGPoint(x: 92, y: 329.333))
        path.addLineToPoint(CGPoint(x: 92, y: 73.333))
        path.addCurveToPoint(CGPoint(x: 96, y: 69.333), controlPoint1: CGPoint(x: 92, y: 71.067), controlPoint2: CGPoint(x: 93.733, y: 69.333))
        path.addLineToPoint(CGPoint(x: 178, y: 69.333))
        path.addCurveToPoint(CGPoint(x: 230.267, y: 79.2), controlPoint1: CGPoint(x: 196.8, y: 69.333), controlPoint2: CGPoint(x: 214.4, y: 72.667))
        path.addCurveToPoint(CGPoint(x: 271.33299999999997, y: 106.533), controlPoint1: CGPoint(x: 246.13299999999998, y: 85.733), controlPoint2: CGPoint(x: 260, y: 94.933))
        path.addCurveToPoint(CGPoint(x: 298, y: 147.867), controlPoint1: CGPoint(x: 282.667, y: 118.133), controlPoint2: CGPoint(x: 291.6, y: 132))
        path.addCurveToPoint(CGPoint(x: 307.467, y: 200.13299999999998), controlPoint1: CGPoint(x: 304.267, y: 163.733), controlPoint2: CGPoint(x: 307.467, y: 181.333))
        path.addCurveToPoint(CGPoint(x: 298, y: 252.39999999999998), controlPoint1: CGPoint(x: 307.467, y: 218.933), controlPoint2: CGPoint(x: 304.267, y: 236.533))
        path.addCurveToPoint(CGPoint(x: 271.33299999999997, y: 293.73299999999995), controlPoint1: CGPoint(x: 291.733, y: 268.267), controlPoint2: CGPoint(x: 282.667, y: 282.267))
        path.addCurveToPoint(CGPoint(x: 230.26699999999997, y: 321.06699999999995), controlPoint1: CGPoint(x: 259.99999999999994, y: 305.33299999999997), controlPoint2: CGPoint(x: 246.13299999999998, y: 314.53299999999996))
        path.addCurveToPoint(CGPoint(x: 177.99999999999997, y: 331.06699999999995), controlPoint1: CGPoint(x: 214.39999999999998, y: 327.73299999999995), controlPoint2: CGPoint(x: 196.79999999999995, y: 331.06699999999995))
        path.closePath()
        path.moveToPoint(CGPoint(x: 99.99999999999997, y: 323.06699999999995))
        path.addLineToPoint(CGPoint(x: 177.99999999999997, y: 323.06699999999995))
        path.addCurveToPoint(CGPoint(x: 227.2, y: 313.73299999999995), controlPoint1: CGPoint(x: 195.73299999999998, y: 323.06699999999995), controlPoint2: CGPoint(x: 212.26699999999997, y: 319.99999999999994))
        path.addCurveToPoint(CGPoint(x: 265.59999999999997, y: 288.1329999999999), controlPoint1: CGPoint(x: 242.13299999999998, y: 307.59999999999997), controlPoint2: CGPoint(x: 254.933, y: 298.93299999999994))
        path.addCurveToPoint(CGPoint(x: 290.53299999999996, y: 249.3329999999999), controlPoint1: CGPoint(x: 276.133, y: 277.3329999999999), controlPoint2: CGPoint(x: 284.53299999999996, y: 264.26699999999994))
        path.addCurveToPoint(CGPoint(x: 299.467, y: 199.99999999999991), controlPoint1: CGPoint(x: 296.53299999999996, y: 234.39999999999992), controlPoint2: CGPoint(x: 299.467, y: 217.8669999999999))
        path.addCurveToPoint(CGPoint(x: 290.53299999999996, y: 150.66699999999992), controlPoint1: CGPoint(x: 299.467, y: 182.2669999999999), controlPoint2: CGPoint(x: 296.4, y: 165.5999999999999))
        path.addCurveToPoint(CGPoint(x: 265.59999999999997, y: 111.86699999999992), controlPoint1: CGPoint(x: 284.53299999999996, y: 135.73299999999992), controlPoint2: CGPoint(x: 276.26699999999994, y: 122.66699999999992))
        path.addCurveToPoint(CGPoint(x: 227.19999999999996, y: 86.26699999999991), controlPoint1: CGPoint(x: 255.06699999999998, y: 101.06699999999992), controlPoint2: CGPoint(x: 242.13299999999998, y: 92.39999999999992))
        path.addCurveToPoint(CGPoint(x: 177.99999999999994, y: 77.33299999999991), controlPoint1: CGPoint(x: 212.26699999999997, y: 80.3999999999999), controlPoint2: CGPoint(x: 195.73299999999995, y: 77.33299999999991))
        path.addLineToPoint(CGPoint(x: 99.99999999999994, y: 77.33299999999991))
        path.addLineToPoint(CGPoint(x: 99.99999999999994, y: 323.0669999999999))
        path.closePath()
        layer1.path = path.CGPath
    })()
    ({
        let layer1 = CAShapeLayer()
        layer1.fillColor = UIColor(red: 1, green: 1, blue:1, alpha: 1).CGColor
        layer1.strokeColor = UIColor(red: 0, green: 0, blue:0, alpha: 0).CGColor
        layer1.lineWidth = 0
        layer1.fillRule = kCAFillRuleEvenOdd
        rootLayer.addSublayer(layer1)
        let path = UIBezierPath()
        path.moveToPoint(CGPoint(x: 178.667, y: 289.733))
        path.addLineToPoint(CGPoint(x: 139.46699999999998, y: 289.733))
        path.addCurveToPoint(CGPoint(x: 135.46699999999998, y: 285.733), controlPoint1: CGPoint(x: 137.2, y: 289.733), controlPoint2: CGPoint(x: 135.46699999999998, y: 288))
        path.addCurveToPoint(CGPoint(x: 139.46699999999998, y: 281.733), controlPoint1: CGPoint(x: 135.46699999999998, y: 283.467), controlPoint2: CGPoint(x: 137.2, y: 281.733))
        path.addLineToPoint(CGPoint(x: 178.66699999999997, y: 281.733))
        path.addCurveToPoint(CGPoint(x: 210.39999999999998, y: 275.2), controlPoint1: CGPoint(x: 190.39999999999998, y: 281.733), controlPoint2: CGPoint(x: 201.06699999999998, y: 279.6))
        path.addCurveToPoint(CGPoint(x: 234.533, y: 257.467), controlPoint1: CGPoint(x: 219.73299999999998, y: 270.8), controlPoint2: CGPoint(x: 227.86699999999996, y: 264.933))
        path.addCurveToPoint(CGPoint(x: 249.867, y: 231.6), controlPoint1: CGPoint(x: 241.2, y: 250), controlPoint2: CGPoint(x: 246.4, y: 241.333))
        path.addCurveToPoint(CGPoint(x: 255.2, y: 200.13299999999998), controlPoint1: CGPoint(x: 253.46699999999998, y: 221.867), controlPoint2: CGPoint(x: 255.2, y: 211.2))
        path.addCurveToPoint(CGPoint(x: 249.867, y: 168.533), controlPoint1: CGPoint(x: 255.2, y: 189.06699999999998), controlPoint2: CGPoint(x: 253.333, y: 178.39999999999998))
        path.addCurveToPoint(CGPoint(x: 234.533, y: 142.66699999999997), controlPoint1: CGPoint(x: 246.267, y: 158.66699999999997), controlPoint2: CGPoint(x: 241.2, y: 150))
        path.addCurveToPoint(CGPoint(x: 210.39999999999998, y: 125.06699999999998), controlPoint1: CGPoint(x: 227.867, y: 135.33299999999997), controlPoint2: CGPoint(x: 219.867, y: 129.46699999999998))
        path.addCurveToPoint(CGPoint(x: 208.39999999999998, y: 119.73299999999998), controlPoint1: CGPoint(x: 208.39999999999998, y: 124.13299999999998), controlPoint2: CGPoint(x: 207.46699999999998, y: 121.73299999999998))
        path.addCurveToPoint(CGPoint(x: 213.73299999999998, y: 117.73299999999998), controlPoint1: CGPoint(x: 209.33299999999997, y: 117.73299999999998), controlPoint2: CGPoint(x: 211.73299999999998, y: 116.79999999999998))
        path.addCurveToPoint(CGPoint(x: 240.39999999999998, y: 137.2), controlPoint1: CGPoint(x: 224.13299999999998, y: 122.53299999999997), controlPoint2: CGPoint(x: 233.06699999999998, y: 129.06699999999998))
        path.addCurveToPoint(CGPoint(x: 257.33299999999997, y: 165.733), controlPoint1: CGPoint(x: 247.73299999999998, y: 145.333), controlPoint2: CGPoint(x: 253.46699999999998, y: 154.933))
        path.addCurveToPoint(CGPoint(x: 263.2, y: 200.133), controlPoint1: CGPoint(x: 261.2, y: 176.53300000000002), controlPoint2: CGPoint(x: 263.2, y: 188))
        path.addCurveToPoint(CGPoint(x: 257.33299999999997, y: 234.267), controlPoint1: CGPoint(x: 263.2, y: 212.133), controlPoint2: CGPoint(x: 261.2, y: 223.60000000000002))
        path.addCurveToPoint(CGPoint(x: 240.39999999999998, y: 262.8), controlPoint1: CGPoint(x: 253.46699999999996, y: 244.933), controlPoint2: CGPoint(x: 247.73299999999998, y: 254.533))
        path.addCurveToPoint(CGPoint(x: 213.73299999999998, y: 282.40000000000003), controlPoint1: CGPoint(x: 233.06699999999998, y: 271.067), controlPoint2: CGPoint(x: 224.13299999999998, y: 277.6))
        path.addCurveToPoint(CGPoint(x: 178.66699999999997, y: 289.73300000000006), controlPoint1: CGPoint(x: 203.33299999999997, y: 287.333), controlPoint2: CGPoint(x: 191.46699999999998, y: 289.73300000000006))
        path.closePath()
        layer1.path = path.CGPath
    })()
    rootLayer.bounds = CGRect(x: 0, y: 0, width: 400, height: 400)
    rootLayer.anchorPoint = CGPoint(x: 0, y: 0)
    
    return rootLayer
}()

var coinOriginalSvg: CAShapeLayer = {
    let rootLayer = CAShapeLayer() // Generated by Svgsus
    ({
        let layer1 = CAShapeLayer()
        layer1.fillColor = UIColor(red: 0, green: 0, blue:0, alpha: 1).CGColor
        layer1.strokeColor = UIColor(red: 0, green: 0, blue:0, alpha: 0).CGColor
        layer1.lineWidth = 0
        layer1.fillRule = kCAFillRuleEvenOdd
        rootLayer.addSublayer(layer1)
        let path = UIBezierPath()
        path.moveToPoint(CGPoint(x: 16, y: 8))
        path.addCurveToPoint(CGPoint(x: 8, y: 0), controlPoint1: CGPoint(x: 16, y: 3.582), controlPoint2: CGPoint(x: 12.418, y: 0))
        path.addCurveToPoint(CGPoint(x: 0, y: 8), controlPoint1: CGPoint(x: 3.5820000000000007, y: 0), controlPoint2: CGPoint(x: 0, y: 3.582))
        path.addCurveToPoint(CGPoint(x: 8, y: 16), controlPoint1: CGPoint(x: 0, y: 12.418), controlPoint2: CGPoint(x: 3.582, y: 16))
        path.addCurveToPoint(CGPoint(x: 16, y: 8), controlPoint1: CGPoint(x: 12.418, y: 16), controlPoint2: CGPoint(x: 16, y: 12.418))
        path.closePath()
        path.moveToPoint(CGPoint(x: 1, y: 8))
        path.addCurveToPoint(CGPoint(x: 8, y: 1), controlPoint1: CGPoint(x: 1, y: 4.134), controlPoint2: CGPoint(x: 4.134, y: 1))
        path.addCurveToPoint(CGPoint(x: 15, y: 8), controlPoint1: CGPoint(x: 11.866, y: 1), controlPoint2: CGPoint(x: 15, y: 4.134))
        path.addCurveToPoint(CGPoint(x: 8, y: 15), controlPoint1: CGPoint(x: 15, y: 11.866), controlPoint2: CGPoint(x: 11.866, y: 15))
        path.addCurveToPoint(CGPoint(x: 1, y: 8), controlPoint1: CGPoint(x: 4.134, y: 15), controlPoint2: CGPoint(x: 1, y: 11.866))
        path.closePath()
        path.moveToPoint(CGPoint(x: 8.382, y: 4.5))
        path.addLineToPoint(CGPoint(x: 8.382, y: 5.1899999999999995))
        path.addCurveToPoint(CGPoint(x: 8.962, y: 5.465999999999999), controlPoint1: CGPoint(x: 8.618, y: 5.234999999999999), controlPoint2: CGPoint(x: 8.812, y: 5.327))
        path.addCurveToPoint(CGPoint(x: 9.392, y: 6.103999999999999), controlPoint1: CGPoint(x: 9.112, y: 5.603999999999999), controlPoint2: CGPoint(x: 9.256, y: 5.816999999999999))
        path.addLineToPoint(CGPoint(x: 8.806, y: 6.4879999999999995))
        path.addCurveToPoint(CGPoint(x: 8.113999999999999, y: 5.9239999999999995), controlPoint1: CGPoint(x: 8.629, y: 6.111999999999999), controlPoint2: CGPoint(x: 8.399, y: 5.9239999999999995))
        path.addCurveToPoint(CGPoint(x: 7.674999999999999, y: 6.106999999999999), controlPoint1: CGPoint(x: 7.937999999999999, y: 5.9239999999999995), controlPoint2: CGPoint(x: 7.791999999999999, y: 5.984999999999999))
        path.addCurveToPoint(CGPoint(x: 7.500999999999999, y: 6.5649999999999995), controlPoint1: CGPoint(x: 7.558999999999999, y: 6.228999999999999), controlPoint2: CGPoint(x: 7.500999999999999, y: 6.382))
        path.addCurveToPoint(CGPoint(x: 7.641999999999999, y: 6.981), controlPoint1: CGPoint(x: 7.500999999999999, y: 6.731999999999999), controlPoint2: CGPoint(x: 7.547999999999998, y: 6.8709999999999996))
        path.addCurveToPoint(CGPoint(x: 8.201999999999998, y: 7.366), controlPoint1: CGPoint(x: 7.733999999999998, y: 7.0889999999999995), controlPoint2: CGPoint(x: 7.9209999999999985, y: 7.218))
        path.addCurveToPoint(CGPoint(x: 8.801999999999998, y: 7.7299999999999995), controlPoint1: CGPoint(x: 8.443999999999999, y: 7.494999999999999), controlPoint2: CGPoint(x: 8.643999999999998, y: 7.616))
        path.addCurveToPoint(CGPoint(x: 9.159999999999998, y: 8.059999999999999), controlPoint1: CGPoint(x: 8.960999999999999, y: 7.843999999999999), controlPoint2: CGPoint(x: 9.079999999999998, y: 7.954))
        path.addCurveToPoint(CGPoint(x: 9.499999999999998, y: 9.099999999999998), controlPoint1: CGPoint(x: 9.386999999999999, y: 8.347), controlPoint2: CGPoint(x: 9.499999999999998, y: 8.692999999999998))
        path.addCurveToPoint(CGPoint(x: 9.192999999999998, y: 10.156999999999998), controlPoint1: CGPoint(x: 9.499999999999998, y: 9.499999999999998), controlPoint2: CGPoint(x: 9.397999999999998, y: 9.851999999999999))
        path.addCurveToPoint(CGPoint(x: 8.381999999999998, y: 10.769999999999998), controlPoint1: CGPoint(x: 8.990999999999998, y: 10.459999999999999), controlPoint2: CGPoint(x: 8.719999999999997, y: 10.665))
        path.addLineToPoint(CGPoint(x: 8.381999999999998, y: 11.499999999999998))
        path.addLineToPoint(CGPoint(x: 7.855999999999998, y: 11.499999999999998))
        path.addLineToPoint(CGPoint(x: 7.855999999999998, y: 10.791999999999998))
        path.addCurveToPoint(CGPoint(x: 6.955999999999998, y: 10.315999999999999), controlPoint1: CGPoint(x: 7.462999999999998, y: 10.715999999999998), controlPoint2: CGPoint(x: 7.1629999999999985, y: 10.557999999999998))
        path.addCurveToPoint(CGPoint(x: 6.499999999999997, y: 9.194999999999999), controlPoint1: CGPoint(x: 6.749999999999997, y: 10.073999999999998), controlPoint2: CGPoint(x: 6.597999999999998, y: 9.7))
        path.addLineToPoint(CGPoint(x: 7.160999999999998, y: 9.032999999999998))
        path.addCurveToPoint(CGPoint(x: 7.491999999999998, y: 9.797999999999998), controlPoint1: CGPoint(x: 7.250999999999998, y: 9.389999999999997), controlPoint2: CGPoint(x: 7.360999999999998, y: 9.644999999999998))
        path.addCurveToPoint(CGPoint(x: 8.035999999999998, y: 10.015999999999998), controlPoint1: CGPoint(x: 7.627999999999998, y: 9.942999999999998), controlPoint2: CGPoint(x: 7.809999999999998, y: 10.015999999999998))
        path.addCurveToPoint(CGPoint(x: 8.588999999999999, y: 9.765999999999998), controlPoint1: CGPoint(x: 8.255999999999998, y: 10.015999999999998), controlPoint2: CGPoint(x: 8.440999999999997, y: 9.932999999999998))
        path.addCurveToPoint(CGPoint(x: 8.809, y: 9.127999999999998), controlPoint1: CGPoint(x: 8.735, y: 9.600999999999999), controlPoint2: CGPoint(x: 8.809, y: 9.388999999999998))
        path.addCurveToPoint(CGPoint(x: 8.625, y: 8.567999999999998), controlPoint1: CGPoint(x: 8.809, y: 8.894999999999998), controlPoint2: CGPoint(x: 8.747, y: 8.707999999999998))
        path.addCurveToPoint(CGPoint(x: 8.35, y: 8.336999999999998), controlPoint1: CGPoint(x: 8.563, y: 8.498999999999997), controlPoint2: CGPoint(x: 8.471, y: 8.421999999999997))
        path.addCurveToPoint(CGPoint(x: 7.885999999999999, y: 8.056999999999999), controlPoint1: CGPoint(x: 8.229, y: 8.250999999999998), controlPoint2: CGPoint(x: 8.074, y: 8.156999999999998))
        path.addCurveToPoint(CGPoint(x: 7.118999999999999, y: 7.491999999999999), controlPoint1: CGPoint(x: 7.496999999999999, y: 7.8519999999999985), controlPoint2: CGPoint(x: 7.241, y: 7.663999999999999))
        path.addCurveToPoint(CGPoint(x: 6.8279999999999985, y: 6.571999999999999), controlPoint1: CGPoint(x: 6.924999999999999, y: 7.235999999999999), controlPoint2: CGPoint(x: 6.8279999999999985, y: 6.929999999999999))
        path.addCurveToPoint(CGPoint(x: 6.8969999999999985, y: 6.1), controlPoint1: CGPoint(x: 6.8279999999999985, y: 6.403), controlPoint2: CGPoint(x: 6.850999999999998, y: 6.2459999999999996))
        path.addCurveToPoint(CGPoint(x: 7.096999999999999, y: 5.704), controlPoint1: CGPoint(x: 6.942999999999999, y: 5.955), controlPoint2: CGPoint(x: 7.009999999999999, y: 5.821999999999999))
        path.addCurveToPoint(CGPoint(x: 7.419999999999999, y: 5.395), controlPoint1: CGPoint(x: 7.183999999999998, y: 5.585), controlPoint2: CGPoint(x: 7.291999999999999, y: 5.481999999999999))
        path.addCurveToPoint(CGPoint(x: 7.855999999999999, y: 5.191), controlPoint1: CGPoint(x: 7.547999999999999, y: 5.308), controlPoint2: CGPoint(x: 7.692999999999999, y: 5.239999999999999))
        path.addLineToPoint(CGPoint(x: 7.855999999999999, y: 4.5))
        path.addLineToPoint(CGPoint(x: 8.382, y: 4.5))
        path.closePath()
        layer1.path = path.CGPath
    })()
    rootLayer.bounds = CGRect(x: 0, y: 0, width: 16, height: 16)
    rootLayer.anchorPoint = CGPoint(x: 0, y: 0)
    
    return rootLayer
}()


