let rootLayer = CAShapeLayer() // Generated by Svgsus
({
  let layer1 = CAShapeLayer()
  layer1.fillColor = NSColor(red: 0, green: 0, blue:0, alpha: 1).CGColor
  layer1.strokeColor = NSColor(red: 0, green: 0, blue:0, alpha: 1).CGColor
  layer1.lineWidth = 0
  layer1.fillRule = kCAFillRuleEvenOdd
  rootLayer.addSublayer(layer1)
  let path = NSBezierPath()
  path.moveToPoint(NSPoint(x: 0, y: 0))
  path.lineToPoint(NSPoint(x: 400, y: 0))
  path.lineToPoint(NSPoint(x: 400, y: 400))
  path.lineToPoint(NSPoint(x: 0, y: 400))
  path.closePath()
  layer1.path = path.CGPath
})()
({
  let layer1 = CAShapeLayer()
  layer1.fillColor = NSColor(red: 1, green: 1, blue:1, alpha: 1).CGColor
  layer1.strokeColor = NSColor(red: 0, green: 0, blue:0, alpha: 1).CGColor
  layer1.lineWidth = 0
  layer1.fillRule = kCAFillRuleEvenOdd
  rootLayer.addSublayer(layer1)
  let path = NSBezierPath()
  path.moveToPoint(NSPoint(x: 178, y: 331.067))
  path.lineToPoint(NSPoint(x: 96, y: 331.067))
  path.curveToPoint(NSPoint(x: 92, y: 327.067), controlPoint1: NSPoint(x: 93.733, y: 331.067), controlPoint2: NSPoint(x: 92, y: 329.333))
  path.lineToPoint(NSPoint(x: 92, y: 73.333))
  path.curveToPoint(NSPoint(x: 96, y: 69.333), controlPoint1: NSPoint(x: 92, y: 71.067), controlPoint2: NSPoint(x: 93.733, y: 69.333))
  path.lineToPoint(NSPoint(x: 178, y: 69.333))
  path.curveToPoint(NSPoint(x: 230.267, y: 79.2), controlPoint1: NSPoint(x: 196.8, y: 69.333), controlPoint2: NSPoint(x: 214.4, y: 72.667))
  path.curveToPoint(NSPoint(x: 271.33299999999997, y: 106.533), controlPoint1: NSPoint(x: 246.13299999999998, y: 85.733), controlPoint2: NSPoint(x: 260, y: 94.933))
  path.curveToPoint(NSPoint(x: 298, y: 147.867), controlPoint1: NSPoint(x: 282.667, y: 118.133), controlPoint2: NSPoint(x: 291.6, y: 132))
  path.curveToPoint(NSPoint(x: 307.467, y: 200.13299999999998), controlPoint1: NSPoint(x: 304.267, y: 163.733), controlPoint2: NSPoint(x: 307.467, y: 181.333))
  path.curveToPoint(NSPoint(x: 298, y: 252.39999999999998), controlPoint1: NSPoint(x: 307.467, y: 218.933), controlPoint2: NSPoint(x: 304.267, y: 236.533))
  path.curveToPoint(NSPoint(x: 271.33299999999997, y: 293.73299999999995), controlPoint1: NSPoint(x: 291.733, y: 268.267), controlPoint2: NSPoint(x: 282.667, y: 282.267))
  path.curveToPoint(NSPoint(x: 230.26699999999997, y: 321.06699999999995), controlPoint1: NSPoint(x: 259.99999999999994, y: 305.33299999999997), controlPoint2: NSPoint(x: 246.13299999999998, y: 314.53299999999996))
  path.curveToPoint(NSPoint(x: 177.99999999999997, y: 331.06699999999995), controlPoint1: NSPoint(x: 214.39999999999998, y: 327.73299999999995), controlPoint2: NSPoint(x: 196.79999999999995, y: 331.06699999999995))
  path.closePath()
  path.moveToPoint(NSPoint(x: 99.99999999999997, y: 323.06699999999995))
  path.lineToPoint(NSPoint(x: 177.99999999999997, y: 323.06699999999995))
  path.curveToPoint(NSPoint(x: 227.2, y: 313.73299999999995), controlPoint1: NSPoint(x: 195.73299999999998, y: 323.06699999999995), controlPoint2: NSPoint(x: 212.26699999999997, y: 319.99999999999994))
  path.curveToPoint(NSPoint(x: 265.59999999999997, y: 288.1329999999999), controlPoint1: NSPoint(x: 242.13299999999998, y: 307.59999999999997), controlPoint2: NSPoint(x: 254.933, y: 298.93299999999994))
  path.curveToPoint(NSPoint(x: 290.53299999999996, y: 249.3329999999999), controlPoint1: NSPoint(x: 276.133, y: 277.3329999999999), controlPoint2: NSPoint(x: 284.53299999999996, y: 264.26699999999994))
  path.curveToPoint(NSPoint(x: 299.467, y: 199.99999999999991), controlPoint1: NSPoint(x: 296.53299999999996, y: 234.39999999999992), controlPoint2: NSPoint(x: 299.467, y: 217.8669999999999))
  path.curveToPoint(NSPoint(x: 290.53299999999996, y: 150.66699999999992), controlPoint1: NSPoint(x: 299.467, y: 182.2669999999999), controlPoint2: NSPoint(x: 296.4, y: 165.5999999999999))
  path.curveToPoint(NSPoint(x: 265.59999999999997, y: 111.86699999999992), controlPoint1: NSPoint(x: 284.53299999999996, y: 135.73299999999992), controlPoint2: NSPoint(x: 276.26699999999994, y: 122.66699999999992))
  path.curveToPoint(NSPoint(x: 227.19999999999996, y: 86.26699999999991), controlPoint1: NSPoint(x: 255.06699999999998, y: 101.06699999999992), controlPoint2: NSPoint(x: 242.13299999999998, y: 92.39999999999992))
  path.curveToPoint(NSPoint(x: 177.99999999999994, y: 77.33299999999991), controlPoint1: NSPoint(x: 212.26699999999997, y: 80.3999999999999), controlPoint2: NSPoint(x: 195.73299999999995, y: 77.33299999999991))
  path.lineToPoint(NSPoint(x: 99.99999999999994, y: 77.33299999999991))
  path.lineToPoint(NSPoint(x: 99.99999999999994, y: 323.0669999999999))
  path.closePath()
  layer1.path = path.CGPath
})()
({
  let layer1 = CAShapeLayer()
  layer1.fillColor = NSColor(red: 1, green: 1, blue:1, alpha: 1).CGColor
  layer1.strokeColor = NSColor(red: 0, green: 0, blue:0, alpha: 1).CGColor
  layer1.lineWidth = 0
  layer1.fillRule = kCAFillRuleEvenOdd
  rootLayer.addSublayer(layer1)
  let path = NSBezierPath()
  path.moveToPoint(NSPoint(x: 178.667, y: 289.733))
  path.lineToPoint(NSPoint(x: 139.46699999999998, y: 289.733))
  path.curveToPoint(NSPoint(x: 135.46699999999998, y: 285.733), controlPoint1: NSPoint(x: 137.2, y: 289.733), controlPoint2: NSPoint(x: 135.46699999999998, y: 288))
  path.curveToPoint(NSPoint(x: 139.46699999999998, y: 281.733), controlPoint1: NSPoint(x: 135.46699999999998, y: 283.467), controlPoint2: NSPoint(x: 137.2, y: 281.733))
  path.lineToPoint(NSPoint(x: 178.66699999999997, y: 281.733))
  path.curveToPoint(NSPoint(x: 210.39999999999998, y: 275.2), controlPoint1: NSPoint(x: 190.39999999999998, y: 281.733), controlPoint2: NSPoint(x: 201.06699999999998, y: 279.6))
  path.curveToPoint(NSPoint(x: 234.533, y: 257.467), controlPoint1: NSPoint(x: 219.73299999999998, y: 270.8), controlPoint2: NSPoint(x: 227.86699999999996, y: 264.933))
  path.curveToPoint(NSPoint(x: 249.867, y: 231.6), controlPoint1: NSPoint(x: 241.2, y: 250), controlPoint2: NSPoint(x: 246.4, y: 241.333))
  path.curveToPoint(NSPoint(x: 255.2, y: 200.13299999999998), controlPoint1: NSPoint(x: 253.46699999999998, y: 221.867), controlPoint2: NSPoint(x: 255.2, y: 211.2))
  path.curveToPoint(NSPoint(x: 249.867, y: 168.533), controlPoint1: NSPoint(x: 255.2, y: 189.06699999999998), controlPoint2: NSPoint(x: 253.333, y: 178.39999999999998))
  path.curveToPoint(NSPoint(x: 234.533, y: 142.66699999999997), controlPoint1: NSPoint(x: 246.267, y: 158.66699999999997), controlPoint2: NSPoint(x: 241.2, y: 150))
  path.curveToPoint(NSPoint(x: 210.39999999999998, y: 125.06699999999998), controlPoint1: NSPoint(x: 227.867, y: 135.33299999999997), controlPoint2: NSPoint(x: 219.867, y: 129.46699999999998))
  path.curveToPoint(NSPoint(x: 208.39999999999998, y: 119.73299999999998), controlPoint1: NSPoint(x: 208.39999999999998, y: 124.13299999999998), controlPoint2: NSPoint(x: 207.46699999999998, y: 121.73299999999998))
  path.curveToPoint(NSPoint(x: 213.73299999999998, y: 117.73299999999998), controlPoint1: NSPoint(x: 209.33299999999997, y: 117.73299999999998), controlPoint2: NSPoint(x: 211.73299999999998, y: 116.79999999999998))
  path.curveToPoint(NSPoint(x: 240.39999999999998, y: 137.2), controlPoint1: NSPoint(x: 224.13299999999998, y: 122.53299999999997), controlPoint2: NSPoint(x: 233.06699999999998, y: 129.06699999999998))
  path.curveToPoint(NSPoint(x: 257.33299999999997, y: 165.733), controlPoint1: NSPoint(x: 247.73299999999998, y: 145.333), controlPoint2: NSPoint(x: 253.46699999999998, y: 154.933))
  path.curveToPoint(NSPoint(x: 263.2, y: 200.133), controlPoint1: NSPoint(x: 261.2, y: 176.53300000000002), controlPoint2: NSPoint(x: 263.2, y: 188))
  path.curveToPoint(NSPoint(x: 257.33299999999997, y: 234.267), controlPoint1: NSPoint(x: 263.2, y: 212.133), controlPoint2: NSPoint(x: 261.2, y: 223.60000000000002))
  path.curveToPoint(NSPoint(x: 240.39999999999998, y: 262.8), controlPoint1: NSPoint(x: 253.46699999999996, y: 244.933), controlPoint2: NSPoint(x: 247.73299999999998, y: 254.533))
  path.curveToPoint(NSPoint(x: 213.73299999999998, y: 282.40000000000003), controlPoint1: NSPoint(x: 233.06699999999998, y: 271.067), controlPoint2: NSPoint(x: 224.13299999999998, y: 277.6))
  path.curveToPoint(NSPoint(x: 178.66699999999997, y: 289.73300000000006), controlPoint1: NSPoint(x: 203.33299999999997, y: 287.333), controlPoint2: NSPoint(x: 191.46699999999998, y: 289.73300000000006))
  path.closePath()
  layer1.path = path.CGPath
})()
let scaleTransform = CATransform3DMakeScale(1, -1, 1)
let translateTransform = CATransform3DMakeTranslation(0, 400, 0)
let transform = CATransform3DConcat(scaleTransform, translateTransform)
rootLayer.transform = transform
rootLayer.bounds = CGRect(x: 0, y: 0, width: 400, height: 400)
rootLayer.anchorPoint = CGPoint(x: 0, y: 0)
